name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  country_picker: ^2.0.22
  firebase_core: ^2.30.0
  firebase_auth: ^4.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  sign_in_with_apple: ^6.1.0
  image_picker: ^1.1.0
  permission_handler: ^11.3.0
  geolocator: ^11.0.0
  google_maps_flutter_web: ^0.5.4+2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  google_maps_flutter: ^2.6.0
  pin_code_fields: ^8.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/india_flag.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/apple.png
    - assets/images/car.png
    - assets/images/bike.png
    - assets/images/auto.png
    - assets/images/location1.png
    - assets/images/cloud 2.png
    - assets/images/cloud 3.png
    - assets/images/email_icon.png
    - assets/images/car.png
    - assets/images/doraemon.png